[tool.poetry]
name = "fastapi-quick-started"
version = "0.1.0"
description = ""
authors = ["Allen Chou <f1470891079@gmail.com>"]
license = "Apache-2.0 license"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
fastapi = {extras = ["all"], version = "^0.104.1"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pydantic = "^2.5.2"
pydantic-settings = "^2.1.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
pytz = "^2023.3.post1"
rich = "^13.7.0"
uvicorn = {extras = ["standard"], version = "^0.24.0.post1"}

[tool.poetry.extras]
all = []

[tool.poetry.group.dev.dependencies]
poetry-plugin-export = "^1.6.0"
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
